version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_PORT=3000
        - REACT_APP_MQTT_BROKER=localhost
        - REACT_APP_MQTT_PORT=1883
        - REACT_APP_MQTT_WEBSOCKET_PORT=9001
    container_name: home-zigbee-network-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: npm run start
    volumes:
      - ./frontend/src:/usr/src/app/src
  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: home-zigbee-network-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
#  zigbe2mqtt:
#    image: zigbee2mqtt/zigbee2mqtt-armv7:1.21.1-1
#    container_name: home-zigbee-network-zigbee2mqtt