version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_PORT=3000
        - REACT_APP_MQTT_BROKER_HOST=raspberrypi.local
        - REACT_APP_MQTT_BROKER_WS_PORT=8083
        - REACT_APP_DEFAULT_TOPIC=zigbee2mqtt/+
    environment:
      CHOKIDAR_USEPOLLING: "true"
    container_name: home-zigbee-network-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: npm run start
    volumes:
      - ./frontend/src:/usr/src/app/src
    networks:
      - home-zigbee-network-network

  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: home-zigbee-network-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
    networks:
      - home-zigbee-network-network

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    container_name: home-zigbee-network-zigbee2mqtt
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./zigbee2mqtt/data:/app/data
    #      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto
    networks:
      - home-zigbee-network-network

  influxdb:
    image: influxdb:1.8.9
    restart: unless-stopped
    container_name: home-zigbee-network-influxdb
    ports:
      - "8086:8086"
    networks:
      - home-zigbee-network-network
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/init:/docker-entrypoint-initdb.d
#      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    environment:
      - INFLUXDB_ADMIN_USER=$INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_TELEGRAF_USER=${INFLUXDB_TELEGRAF_USER}
      - INFLUXDB_TELEGRAF_PASSWORD=${INFLUXDB_TELEGRAF_PASSWORD}
      - INFLUXDB_GRAFANA_USER=${INFLUXDB_GRAFANA_USER}
      - INFLUXDB_GRAFANA_PASSWORD=${INFLUXDB_GRAFANA_PASSWORD}

  telegraf:
    image: telegraf:1.21.1
    restart: unless-stopped
    container_name: home-zigbee-network-telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mosquitto
      - influxdb
    networks:
      - home-zigbee-network-network
    environment:
      - INFLUXDB_TELEGRAF_USER=${INFLUXDB_TELEGRAF_USER}
      - INFLUXDB_TELEGRAF_PASSWORD=${INFLUXDB_TELEGRAF_PASSWORD}

  grafana:
    image: grafana/grafana:main
    restart: unless-stopped
    container_name: home-zigbee-network-grafana
    ports:
      - "3003:3000"
    #user: '104'
    depends_on:
      - influxdb
    networks:
      - home-zigbee-network-network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - INFLUXDB_GRAFANA_USER=${INFLUXDB_GRAFANA_USER}
      - INFLUXDB_GRAFANA_PASSWORD=${INFLUXDB_GRAFANA_PASSWORD}

#  nginx:
#    image: nginx:stable-alpine
#    container_name: home-zigbee-network-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d
#    depends_on:
#      - frontend
#    networks:
#      - home-zigbee-network-network

networks:
  home-zigbee-network-network:
    driver: bridge