version: '3'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_PORT=3000
        - REACT_APP_MQTT_BROKER_HOST=raspberrypi.local
        - REACT_APP_MQTT_BROKER_WS_PORT=8083
        - REACT_APP_DEFAULT_TOPIC=zigbee2mqtt/+
    container_name: home-zigbee-network-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    stdin_open: true
    tty: true
    command: npm run start
    volumes:
      - ./frontend/src:/usr/src/app/src
    networks:
      - home-zigbee-network-network

  mosquitto:
    image: eclipse-mosquitto:1.6.12
    container_name: home-zigbee-network-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
    networks:
      - home-zigbee-network-network

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    container_name: home-zigbee-network-zigbee2mqtt
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Moscow
    volumes:
      - ./zigbee2mqtt/data:/app/data
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto
    networks:
      - home-zigbee-network-network

networks:
  home-zigbee-network-network:
    driver: bridge