services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: zigbee-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
    networks:
      - zigbee-network
    healthcheck:
      test: [ "CMD", "mosquitto_sub", "-h", "localhost", "-t", "$SYS/broker/version", "-C", "1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    container_name: zigbee-zigbee2mqtt
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      mosquitto:
        condition: service_started
    networks:
      - zigbee-network

  influxdb:
    image: influxdb:3.10.1-core
    restart: unless-stopped
    container_name: zigbee-influxdb
    ports:
      - "8181:8181"
    networks:
      - zigbee-network
    volumes:
      - ./influxdb/data:/var/lib/influxdb3
    command:
      - influxdb3
      - serve
      - --node-id
      - node0
      - --object-store
      - file
      - --data-dir
      - /var/lib/influxdb3
    environment:
      - INFLUXDB3_DATABASE=${INFLUXDB3_DATABASE}
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - TZ=Asia/Jerusalem

  explorer:
    image: influxdata/influxdb3-ui:1.9.0
    container_name: influxdb3-explorer
    ports:
      - "127.0.0.1:8888:8080"
    volumes:
      - ./config:/app-root/config:ro
    restart: unless-stopped

  telegraf:
    image: telegraf:1.39.1-alpine
    restart: unless-stopped
    container_name: zigbee-telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      influxdb:
        condition: service_started
        restart: true
      mosquitto:
        condition: service_started
    networks:
      - zigbee-network
    environment:
      - INFLUX_DATABASE=${INFLUXDB3_DATABASE}
      - INFLUX_TOKEN=${INFLUX_TOKEN}

networks:
  zigbee-network:
    driver: bridge