services:
  #  frontend:
  #    build:
  #      context: ./frontend
  #      args:
  #        - REACT_APP_PORT=3000
  #        - REACT_APP_MQTT_BROKER_HOST=raspberrypi.local
  #        - REACT_APP_MQTT_BROKER_WS_PORT=8083
  #        - REACT_APP_DEFAULT_TOPIC=zigbee2mqtt/+
  #    environment:
  #      CHOKIDAR_USEPOLLING: "true"
  #    container_name: zigbee-frontend
  #    ports:
  #      - "3000:3000"
  #    restart: unless-stopped
  #    stdin_open: true
  #    tty: true
  #    command: npm run start
  #    volumes:
  #      - ./frontend/src:/usr/src/app/src
  #    networks:
  #      - zigbee-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: zigbee-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
      - "9001:9001"
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log/mosquitto.log:/mosquitto/log/mosquitto.log
    networks:
      - zigbee-network
    healthcheck:
      test: [ "CMD", "mosquitto_sub", "-h", "localhost", "-t", "$SYS/broker/version", "-C", "1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zigbee2mqtt:
    image: ghcr.io/koenkk/zigbee2mqtt:latest
    restart: unless-stopped
    container_name: zigbee-zigbee2mqtt
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      mosquitto:
        condition: service_started
    networks:
      - zigbee-network

  influxdb:
    image: influxdb:3.10.1-core
    restart: unless-stopped
    container_name: zigbee-influxdb
    ports:
      - "8181:8181"
    networks:
      - zigbee-network
    volumes:
      - ./influxdb/data:/data
    #      - ./influxdb/init:/docker-entrypoint-initdb.d
    #      - ./influxdb/influxdb.conf:/etc/influxdb/influxdb.conf
    command:
      - influxdb3
      - serve
      - --node-id
      - node0
      - --object-store
      - file
      - --data-dir
      - /var/lib/influxdb3
      - --auth-token
      - ${INFLUXDB3_ADMIN_TOKEN}
    environment:
      - INFLUXDB3_DATABASE=${INFLUXDB3_DATABASE}
      - INFLUXDB3_ADMIN_TOKEN=${INFLUXDB3_ADMIN_TOKEN}
      - TZ=Asia/Jerusalem
    healthcheck:
      test: [ "CMD", "influx", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  telegraf:
    image: telegraf:1.39.1-alpine
    restart: unless-stopped
    container_name: zigbee-telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      influxdb:
        condition: service_healthy
        restart: true
      mosquitto:
        condition: service_started
    networks:
      - zigbee-network
    environment:
      - INFLUX_DATABASE=${INFLUXDB3_DATABASE}
      - INFLUX_TOKEN=${INFLUXDB_TELEGRAF_TOKEN}

#  grafana:
#    image: grafana/grafana:main
#    restart: unless-stopped
#    container_name: zigbee-grafana
#    ports:
#      - "3003:3000"
#    #user: '104'
#    depends_on:
#      - influxdb
#    networks:
#      - zigbee-network
#    volumes:
#      - ./grafana/provisioning:/etc/grafana/provisioning
#    environment:
#      - INFLUXDB_DATABASE=${INFLUXDB_BUCKET}
#      - INFLUXDB_GRAFANA_USER=${INFLUXDB_GRAFANA_USER}
#      - INFLUXDB_GRAFANA_PASSWORD=${INFLUXDB_GRAFANA_PASSWORD}

#  nginx:
#    image: nginx:stable-alpine
#    container_name: zigbee-nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d
#    depends_on:
#      - frontend
#    networks:
#      - zigbee-network

networks:
  zigbee-network:
    driver: bridge