apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    url: http://influxdb:8086
    access: proxy
    database: telegraf
    user: $INFLUXDB_GRAFANA_USER
    secureJsonData:
      password: $INFLUXDB_GRAFANA_PASSWORD
    isDefault: true
    editable: true