#!/bin/bash

influx -username $INFLUXDB_ADMIN_USER -password $INFLUXDB_ADMIN_PASSWORD -execute "CREATE DATABASE telegraf WITH DURATION 31d
        CREATE USER $INFLUXDB_TELEGRAF_USER WITH PASSWORD '$INFLUXDB_TELEGRAF_PASSWORD'
        GRANT WRITE ON $INFLUXDB_TELEGRAF_USER to telegraf"
