[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8181"]
  token = "${INFLUX_TOKEN}"
  organization = "Home"
  bucket = "${INFLUX_DATABASE}"

[[outputs.file]]
  files = ["stdout"]

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = [
    "zigbee2mqtt/+",
    "!zigbee2mqtt/bridge/#"
  ]
  name_override = "zigbee_sensor"
  topic_tag = "device"
  data_format = "json"

  fieldexclude = [
    "comfort_humidity_max",
    "comfort_humidity_min",
    "comfort_temperature_max",
    "comfort_temperature_min",
    "humidity_calibration",
    "temperature_calibration",
    "temperature_units",
    "last_seen"
  ]

[[processors.regex]]
  namepass = ["zigbee_sensor"]

  [[processors.regex.tags]]
    key = "device"
    pattern = "^zigbee2mqtt/(.+)$"
    replacement = "${1}"